name: Auto Post to X.com

on:
  workflow_dispatch: # Tombol untuk menjalankan manual di tab Actions
  schedule:
    # Menjalankan 4x sehari, di jam potensial untuk audiens US (UTC)
    # 13:00 UTC -> 9 AM ET (Pagi East Coast)
    # 17:00 UTC -> 1 PM ET / 10 AM PT (Siang East Coast / Pagi West Coast)
    # 22:00 UTC -> 6 PM ET / 3 PM PT (Sore)
    # 03:00 UTC -> 11 PM ET / 8 PM PT (Malam)
    - cron: '0 13,22,3 * * *'

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Auto Post Script
        # Menggunakan env untuk memasukkan API keys dari GitHub Secrets
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: python main.py
